# Generated by Django 6.0.3 on 2026-04-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='serviceitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='order',
        ),
    ]
