# Generated by Django 6.0.3 on 2026-04-05 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='icon',
            field=models.CharField(default='fas fa-cog', max_length=100),
        ),
    ]
