# Generated by Django 6.0.3 on 2026-04-05 15:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_servicecategory_created_at_serviceitem_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Temporary', 'Temporary'), ('Remote', 'Remote'), ('Internship', 'Internship')], max_length=20)),
                ('work_hours', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time')], max_length=20)),
                ('stipend', models.CharField(max_length=50)),
                ('date_published', models.DateField(default=django.utils.timezone.now)),
                ('closing_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JobContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_title_level', models.CharField(choices=[('H1', 'H1'), ('H2', 'H2')], max_length=2)),
                ('opening_title_text', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('H2', 'H2'), ('H3', 'H3'), ('H4', 'H4')], max_length=2)),
                ('format_type', models.CharField(choices=[('paragraph', 'Paragraph'), ('bullet', 'Bullet Points')], max_length=10)),
                ('content_text', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='myApp.job')),
            ],
        ),
    ]
