# Generated by Django 6.0.3 on 2026-04-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_job_jobcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcontent',
            name='job',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobContent',
        ),
    ]
