# Generated by Django 6.0.3 on 2026-04-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_jobpost_jobpostcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareersMainTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='JOIN THE TEAM', max_length=200)),
                ('hero_title', models.CharField(default='Careers at SJS Company', max_length=255)),
                ('intro_title', models.CharField(default='Build Your Career With Us', max_length=255)),
                ('intro_text', models.TextField(blank=True)),
                ('open_positions_title', models.CharField(default='Open Positions', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
