# Generated by Django 6.0.3 on 2026-04-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_careersmaintopics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careersmaintopics',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careersmaintopics',
            name='intro_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careersmaintopics',
            name='intro_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careersmaintopics',
            name='open_positions_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careersmaintopics',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
