# Generated by Django 6.0.3 on 2026-04-13 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_careersmaintopics_hero_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=255)),
                ('hero_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MainTopicBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TopicDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='myApp.maintopicbox')),
            ],
        ),
    ]
