# Generated by Django 6.0.3 on 2026-04-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_contacthero_maintopicbox_topicdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=255)),
                ('hero_title', models.CharField(max_length=255)),
            ],
        ),
    ]
