# Generated by Django 6.0.3 on 2026-04-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_serviceshero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceshero',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceshero',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
