# Generated by Django 6.0.3 on 2026-04-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_alter_serviceshero_hero_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
