# Generated by Django 6.0.3 on 2026-04-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_homehero'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('paragraph1', models.TextField(blank=True, null=True)),
                ('paragraph2', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_about/')),
                ('years', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicles', models.CharField(blank=True, max_length=10, null=True)),
                ('deliveries', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
