# Generated by Django 6.0.3 on 2026-04-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_homeserviceitem_homeservices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeservices',
            old_name='subtitle',
            new_name='section_subtitle',
        ),
        migrations.RenameField(
            model_name='homeservices',
            old_name='title',
            new_name='section_title',
        ),
        migrations.RemoveField(
            model_name='homeserviceitem',
            name='created_at',
        ),
        migrations.AddField(
            model_name='homeservices',
            name='services_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
