# Generated by Django 6.0.3 on 2026-04-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_rename_subtitle_homeservices_section_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeserviceitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
