# Generated by Django 6.0.3 on 2026-04-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_homewhy_homewhyitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homewhyitem',
            name='icon',
            field=models.CharField(default='fas fa-truck', max_length=100),
        ),
    ]
