# Generated by Django 6.0.3 on 2026-04-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_alter_homewhyitem_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_header/')),
            ],
        ),
    ]
