# Generated by Django 6.0.3 on 2026-04-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_footercontactitem_footerserviceitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterLink',
        ),
    ]
