# Generated by Django 6.0.3 on 2026-04-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_delete_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('services', 'Services'), ('careers', 'Careers'), ('contact', 'Contact')], max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='hero_photos/')),
            ],
        ),
    ]
