# Generated by Django 6.0.3 on 2026-06-13 13:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_herophoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abouthero',
            options={'verbose_name': 'Admin About Hero', 'verbose_name_plural': 'Admin About Heros'},
        ),
        migrations.AlterModelOptions(
            name='adminabout',
            options={'verbose_name': 'Admin About', 'verbose_name_plural': 'Admin Abouts'},
        ),
        migrations.AlterModelOptions(
            name='careersmaintopics',
            options={'verbose_name': 'Admin Career Main Topic', 'verbose_name_plural': 'Admin Career Main Topics'},
        ),
        migrations.AlterModelOptions(
            name='contacthero',
            options={'verbose_name': 'Admin Contact Hero', 'verbose_name_plural': 'Admin Contact Heros'},
        ),
        migrations.AlterModelOptions(
            name='corevalue',
            options={'verbose_name': 'Admin About Core Value', 'verbose_name_plural': 'Admin About Core Values'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Admin Footer', 'verbose_name_plural': 'Admin Footers'},
        ),
        migrations.AlterModelOptions(
            name='footercontactitem',
            options={'verbose_name': 'Admin Footer Contact Item', 'verbose_name_plural': 'Admin Footer Contact Items'},
        ),
        migrations.AlterModelOptions(
            name='footerserviceitem',
            options={'verbose_name': 'Admin Footer Service Item', 'verbose_name_plural': 'Admin Footer Service Items'},
        ),
        migrations.AlterModelOptions(
            name='herophoto',
            options={'verbose_name': 'Admin Hero Photo', 'verbose_name_plural': 'Admin Hero Photos'},
        ),
        migrations.AlterModelOptions(
            name='homeabout',
            options={'verbose_name': 'Admin Home About', 'verbose_name_plural': 'Admin Home Abouts'},
        ),
        migrations.AlterModelOptions(
            name='homehero',
            options={'verbose_name': 'Admin Home Hero', 'verbose_name_plural': 'Admin Home Heros'},
        ),
        migrations.AlterModelOptions(
            name='homeserviceitem',
            options={'verbose_name': 'Admin Home Service Item', 'verbose_name_plural': 'Admin Home Service Items'},
        ),
        migrations.AlterModelOptions(
            name='homeservices',
            options={'verbose_name': 'Admin Home Service', 'verbose_name_plural': 'Admin Home Services'},
        ),
        migrations.AlterModelOptions(
            name='homewhy',
            options={'verbose_name': 'Admin Home Why', 'verbose_name_plural': 'Admin Home Whys'},
        ),
        migrations.AlterModelOptions(
            name='homewhyitem',
            options={'verbose_name': 'Admin Home Why Item', 'verbose_name_plural': 'Admin Home Why Items'},
        ),
        migrations.AlterModelOptions(
            name='jobpost',
            options={'verbose_name': 'Admin Career Job Post', 'verbose_name_plural': 'Admin Career Job Posts'},
        ),
        migrations.AlterModelOptions(
            name='jobpostcontent',
            options={'verbose_name': 'Admin Career Job Post Content', 'verbose_name_plural': 'Admin Career Job Post Contents'},
        ),
        migrations.AlterModelOptions(
            name='maintopicbox',
            options={'verbose_name': 'Admin Contact Main Topic Box', 'verbose_name_plural': 'Admin Contact Main Topic Boxs'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='quoterequest',
            options={'verbose_name': 'User Quote Request Service', 'verbose_name_plural': 'User Quote Request Services'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Admin Service Category', 'verbose_name_plural': 'Admin Service Categories'},
        ),
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'verbose_name': 'Admin Service Item', 'verbose_name_plural': 'Admin Service Items'},
        ),
        migrations.AlterModelOptions(
            name='serviceshero',
            options={'verbose_name': 'Admin Service Hero', 'verbose_name_plural': 'Admin Service Heros'},
        ),
        migrations.AlterModelOptions(
            name='siteheader',
            options={'verbose_name': 'Admin Site Header', 'verbose_name_plural': 'Admin Site Headers'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Admin About Team Member', 'verbose_name_plural': 'Admin About Team Members'},
        ),
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'verbose_name': 'Admin About Timeline Event', 'verbose_name_plural': 'Admin About Timeline Events'},
        ),
        migrations.AlterModelOptions(
            name='topicdescription',
            options={'verbose_name': 'Admin Contact Topic Description', 'verbose_name_plural': 'Admin Contact Topic Descriptions'},
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
