# Generated by Django 6.0.3 on 2026-06-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_alter_profile_options_remove_profile_emergency_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='reason_for_leaving',
            field=models.TextField(blank=True, null=True),
        ),
    ]
