# Generated by Django 6.0.3 on 2026-06-17 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0030_alter_education_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='qualification_certificate',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myApp.profile'),
        ),
        migrations.CreateModel(
            name='QualificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='qualifications/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.profile')),
            ],
        ),
    ]
