# Generated by Django 6.0.3 on 2026-06-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0032_alter_workexperience_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corevalue',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Admin About Core Value', 'verbose_name_plural': 'Admin About Core Values'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Admin About Team Member', 'verbose_name_plural': 'Admin About Team Members'},
        ),
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['order', 'year'], 'verbose_name': 'Admin About Timeline Event', 'verbose_name_plural': 'Admin About Timeline Events'},
        ),
    ]
