# Generated by Django 6.0.3 on 2026-06-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0033_alter_corevalue_options_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
