# Generated by Django 6.0.3 on 2026-06-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0035_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('listed', 'Listed'), ('approved', 'Approved by Admin'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
