# Generated by Django 5.0.6 on 2026-07-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0036_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herophoto',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='hero_photos/'),
        ),
    ]
